version: '3.8'
name: brewup

services:
  brewup-app:
    image: ${DOCKER_REGISTRY-}brewup
    container_name: brewup-app
    depends_on:
      - eventstoredb
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MySecretKey
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/BrewUp.pfx
      - MONGODB_URL=mongodb://brewup-mongodb:27017/brewup-app
    ports:
      - target: 80
        published: 5000
        protocol: tcp
        mode: host
      - target: 443
        published: 5001
        protocol: tcp
        mode: host
    working_dir: /app
    volumes:
      - .:/src
      - ~/.aspnet/https:/root/.aspnet/https:ro
    build:
      context: .
      dockerfile: Dockerfile

  eventstoredb:
    image: eventstore/eventstore
    container_name: brewup-eventstoredb
    restart: unless-stopped
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - data:/data/db
    networks:
      - brewup-network

  mongodb:
    image: mongo:latest
    container_name: brewup-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - data:/data/db
    networks:
      - brewup-network

  mongo-express:
    image: mongo-express
    container_name: brewup-mongo-express
    depends_on:
      - mongodb
    restart: always
    ports:
      - "29017:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: brewup-mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_URL: mongodb://root:password@brewup-mongodb:27017/
    volumes:
      - data:/data/db

    networks:
      - brewup-network

volumes:
  data: # override it with your local configuration

networks:
  brewup-network:
    driver: bridge