version: '3.4'

services:
  brewup:
    image: ${DOCKER_REGISTRY-}brewup
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    build:
      context: .
      dockerfile: Dockerfile
